[server]
port = 5562

[node]
detect-drivers = false

[relay]
url = "http://localhost:4722"
status-endpoint = "/status"
configs = [
    "1", "{\"platformName\": \"Android\", \"appium:deviceName\": \"Pixel 2XL\", \"appium:platformVersion\": \"10\", \"appium:udid\": \"192.168.19.56:5555\",	\"appium:appPackage\": \"com.android.settings\", \"appium:appActivity\": \"com.android.settings.Settings\", \"appium:automationName\": \"uiautomator2\", \"appium:noReset\": true, \"appium:newCommandTimeout\": 3600}"]
