[server]
port = 5582

[node]
detect-drivers = false

[relay]
url = "http://localhost:4725"
status-endpoint = "/status"
configs = [
    "1", "{\"platformName\": \"Android\", \"appium:deviceName\": \"Galaxy S21\", \"appium:platformVersion\": \"11\", \"appium:udid\": \"192.168.19.65:5555\",	\"appium:appPackage\": \"com.android.settings\", \"appium:appActivity\": \"com.android.settings.Settings\", \"appium:automationName\": \"uiautomator2\", \"appium:noReset\": true, \"appium:newCommandTimeout\": 3600}"]
