[server]
port = 5570

[node]
detect-drivers = false

[relay]
url = "http://localhost:4722"
status-endpoint = "/status"
configs = [
    "1", "{\"platformName\": \"Android\", \"appium:deviceName\": \"Galaxy S22\", \"appium:platformVersion\": \"12\", \"appium:udid\": \"192.168.19.57:5555\",	\"appium:appPackage\": \"com.google.android.gm\", \"appium:appActivity\": \".ConversationListActivityGmail\", \"appium:automationName\": \"uiautomator2\", \"appium:noReset\": true, \"appium:newCommandTimeout\": 3600}"]
