[server]
port = 5561

[node]
detect-drivers = false

[relay]
url = "http://localhost:4724"
status-endpoint = "/status"
configs = [
    "1", "{\"platformName\": \"Android\", \"appium:deviceName\": \"Pixel 7Pro\", \"appium:platformVersion\": \"14\", \"appium:udid\": \"192.168.19.53:5555\",	\"appium:appPackage\": \"com.android.settings\", \"appium:appActivity\": \"com.android.settings.Settings\", \"appium:automationName\": \"uiautomator2\", \"appium:noReset\": true, \"appium:newCommandTimeout\": 3600}"]
