[server]
port = 5600

[node]
detect-drivers = false

[relay]
url = "http://localhost:4726"
status-endpoint = "/status"
configs = [
    "1", "{\"platformName\": \"Android\", \"appium:deviceName\": \"Galaxy ZFold3\", \"appium:platformVersion\": \"11\", \"appium:udid\": \"192.168.19.63:5555\",	\"appium:appPackage\": \"com.google.android.gm\", \"appium:appActivity\": \".ConversationListActivityGmail\", \"appium:automationName\": \"uiautomator2\", \"appium:noReset\": true, \"appium:newCommandTimeout\": 3600}"]
