[server]
port = 5564

[node]
detect-drivers = false

[relay]
url = "http://localhost:4722"
status-endpoint = "/status"
configs = [
    "1", "{\"platformName\": \"Android\", \"appium:deviceName\": \"Galaxy Tab S7Plus\", \"appium:platformVersion\": \"13\", \"appium:udid\": \"R52R80LED2J\",	\"appium:appPackage\": \"com.android.settings\", \"appium:appActivity\": \"com.android.settings.Settings\", \"appium:automationName\": \"uiautomator2\", \"appium:noReset\": true, \"appium:newCommandTimeout\": 3600}"]
